package com.c4networks.vrms.vo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlTransient;

/**
 * Categories generated by MyEclipse Persistence Tools
 */

public class Categories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields

	private Integer categoryId;
	private CustomerDetails customerDetailsByLastModifiedBy;
	private CustomerDetails customerDetailsByCreatedBy;
	private String categoryName;
	private String categoryDesc;
	private Date createdDate;
	private Date lastModifiedDate;
	private String status;
	private Integer price;
	private Set<Categories> movieses = new HashSet<Categories>(0);

	// Constructors

	/** default constructor */
	public Categories() {
	}

	/** minimal constructor */
	public Categories(Integer categoryId,
			CustomerDetails customerDetailsByLastModifiedBy,
			CustomerDetails customerDetailsByCreatedBy, String categoryName,
			Date createdDate, Date lastModifiedDate, String status, Integer price) {
		this.categoryId = categoryId;
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
		this.categoryName = categoryName;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
		this.price = price;
	}

	/** full constructor */
	public Categories(Integer categoryId,
			CustomerDetails customerDetailsByLastModifiedBy,
			CustomerDetails customerDetailsByCreatedBy, String categoryName,
			String categoryDesc, Date createdDate, Date lastModifiedDate,
			String status, Integer price, Set<Categories> movieses) {
		this.categoryId = categoryId;
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
		this.price = price;
		this.movieses = movieses;
	}

	// Property accessors

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@XmlTransient
	public CustomerDetails getCustomerDetailsByLastModifiedBy() {
		return this.customerDetailsByLastModifiedBy;
	}

	public void setCustomerDetailsByLastModifiedBy(
			CustomerDetails customerDetailsByLastModifiedBy) {
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
	}

	@XmlTransient
	public CustomerDetails getCustomerDetailsByCreatedBy() {
		return this.customerDetailsByCreatedBy;
	}

	public void setCustomerDetailsByCreatedBy(
			CustomerDetails customerDetailsByCreatedBy) {
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Categories> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set<Categories> movieses) {
		this.movieses = movieses;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}