package com.c4networks.vrms.vo;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * CustomerDetails generated by MyEclipse Persistence Tools
 */

//@XmlAccessorType(XmlAccessType.FIELD) // while you uncomment this, the nested objects are not getting marshalled.
@XmlType(name = "CustomerDetails", namespace = "http://vo.vrms.c4networks.com/")
@XmlRootElement(name = "CustomerDetails")
public class CustomerDetails implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String vrmsId;
	private String firstName;
	private String lastName;
	private String email;
	private String status;
	private String address;
	private String phone;
	private String mobile;
	private Integer createdBy;
	private Date createdDate;
	private Integer lastModifiedBy;
	private Date lastModifiedDate;

	/** default constructor */
	public CustomerDetails() {
	}

	/** minimal constructor */
	public CustomerDetails(Integer customerId, String vrmsId, String firstName, String lastName, String email,
			String mobile, Integer createdBy, Date createdDate, Integer lastModifiedBy, Date lastModifiedDate,
			String status) {
		this.customerId = customerId;
		this.vrmsId = vrmsId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.mobile = mobile;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
	}

	/** full constructor */
	public CustomerDetails(Integer customerId, String vrmsId, String firstName, String lastName, String email,
			String address, String phone, String mobile, Integer createdBy, Date createdDate, Integer lastModifiedBy,
			Date lastModifiedDate, String status) {
		this.customerId = customerId;
		this.vrmsId = vrmsId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.address = address;
		this.phone = phone;
		this.mobile = mobile;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.lastModifiedBy = lastModifiedBy;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
	}

	// Property accessors

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(Integer lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getVrmsId() {
		return vrmsId;
	}

	public void setVrmsId(String vrmsId) {
		this.vrmsId = vrmsId;
	}

}