package com.c4networks.vrms.vo;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Movies generated by MyEclipse Persistence Tools
 */

//@XmlAccessorType(XmlAccessType.FIELD) // while you uncomment this, the nested objects are not getting marshalled.
@XmlType(name = "Movies", namespace = "http://vo.vrms.c4networks.com/")
@XmlRootElement(name = "Movies")
public class Movies implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer movieId;
	private String movieName;
	private String movieDesc;
	private Categories categories;
	private Integer copies;
	private CustomerDetails customerDetailsByCreatedBy;
	private Date createdDate;
	private CustomerDetails customerDetailsByLastModifiedBy;
	private Date lastModifiedDate;
	private String status;
	//	private Set<CustomerDetails> rentalDetailses = new HashSet<CustomerDetails>(0);

	// Constructors

	/** default constructor */
	public Movies() {
	}

	/** minimal constructor */
	public Movies(Integer movieId, Categories categories, CustomerDetails customerDetailsByLastModifiedBy,
			CustomerDetails customerDetailsByCreatedBy, String movieName, Integer copies, Date createdDate,
			Date lastModifiedDate) {
		this.movieId = movieId;
		this.categories = categories;
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
		this.movieName = movieName;
		this.copies = copies;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	/** full constructor */
	public Movies(Integer movieId, Categories categories, CustomerDetails customerDetailsByLastModifiedBy,
			CustomerDetails customerDetailsByCreatedBy, String movieName, String movieDesc, Integer copies,
			Date createdDate, Date lastModifiedDate, String status) {
		this.movieId = movieId;
		this.categories = categories;
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
		this.movieName = movieName;
		this.movieDesc = movieDesc;
		this.copies = copies;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
	}

	// Property accessors

	public Integer getMovieId() {
		return this.movieId;
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	//	@XmlTransient
	public CustomerDetails getCustomerDetailsByLastModifiedBy() {
		return this.customerDetailsByLastModifiedBy;
	}

	public void setCustomerDetailsByLastModifiedBy(CustomerDetails customerDetailsByLastModifiedBy) {
		this.customerDetailsByLastModifiedBy = customerDetailsByLastModifiedBy;
	}

	//	@XmlTransient
	public CustomerDetails getCustomerDetailsByCreatedBy() {
		return this.customerDetailsByCreatedBy;
	}

	public void setCustomerDetailsByCreatedBy(CustomerDetails customerDetailsByCreatedBy) {
		this.customerDetailsByCreatedBy = customerDetailsByCreatedBy;
	}

	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	public String getMovieDesc() {
		return this.movieDesc;
	}

	public void setMovieDesc(String movieDesc) {
		this.movieDesc = movieDesc;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	/*	public Set<CustomerDetails> getRentalDetailses() {
			return this.rentalDetailses;
		}
	
		public void setRentalDetailses(Set<CustomerDetails> rentalDetailses) {
			this.rentalDetailses = rentalDetailses;
		}
	*/
	public Integer getCopies() {
		return copies;
	}

	public void setCopies(Integer copies) {
		this.copies = copies;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status
	 *            the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the categories
	 */
	public Categories getCategories() {
		return categories;
	}

	/**
	 * @param categories
	 *            the categories to set
	 */
	public void setCategories(Categories categories) {
		this.categories = categories;
	}

}