package com.c4networks.vrms.vo;

import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

/**
 * RentalDetails generated by MyEclipse Persistence Tools
 */


public class RentalDetails implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rentalDetailsId;
	private Movies movies;
	private CustomerDetails customerDetails;
	private String rentalId;
	private Date rentalDate;
	private Date expectedReturnDate;
	private Date actualReturnDate;
	private Integer bonusPoints;
	private String bonusStatus;
	private Integer lateCharges;
	private String rentalStatus;
	private Integer amount;
	private String comments;

	// Constructors

	/** default constructor */
	public RentalDetails() {
	}

	/** full constructor */
	public RentalDetails(Integer rentalDetailsId, Movies movies,
			CustomerDetails customerDetails, String rentalId, Date rentalDate,
			Date expectedReturnDate, Date actualReturnDate, Integer bonusPoints, String bonusStatus,
			Integer lateCharges, String rentalStatus, Integer amount, String comments) {
		this.rentalDetailsId = rentalDetailsId;
		this.movies = movies;
		this.customerDetails = customerDetails;
		this.rentalId = rentalId;
		this.rentalDate = rentalDate;
		this.expectedReturnDate = expectedReturnDate;
		this.actualReturnDate = actualReturnDate;
		this.bonusPoints = bonusPoints;
		this.bonusStatus = bonusStatus;
		this.lateCharges = lateCharges;
		this.rentalStatus = rentalStatus;
		this.amount = amount;
		this.comments = comments;
	}

	// Property accessors

	public Integer getRentalDetailsId() {
		return this.rentalDetailsId;
	}

	public void setRentalDetailsId(Integer rentalDetailsId) {
		this.rentalDetailsId = rentalDetailsId;
	}

	@XmlTransient
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@XmlTransient
	public CustomerDetails getCustomerDetails() {
		return this.customerDetails;
	}

	public void setCustomerDetails(CustomerDetails customerDetails) {
		this.customerDetails = customerDetails;
	}

	public String getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(String rentalId) {
		this.rentalId = rentalId;
	}

	public Date getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}

	public Integer getBonusPoints() {
		return this.bonusPoints;
	}

	public void setBonusPoints(Integer bonusPoints) {
		this.bonusPoints = bonusPoints;
	}

	public String getBonusStatus() {
		return this.bonusStatus;
	}

	public void setBonusStatus(String bonusStatus) {
		this.bonusStatus = bonusStatus;
	}

	public Integer getLateCharges() {
		return this.lateCharges;
	}

	public void setLateCharges(Integer lateCharges) {
		this.lateCharges = lateCharges;
	}

	public Date getExpectedReturnDate() {
		return expectedReturnDate;
	}

	public void setExpectedReturnDate(Date expectedReturnDate) {
		this.expectedReturnDate = expectedReturnDate;
	}

	public Date getActualReturnDate() {
		return actualReturnDate;
	}

	public void setActualReturnDate(Date actualReturnDate) {
		this.actualReturnDate = actualReturnDate;
	}

	public String getRentalStatus() {
		return rentalStatus;
	}

	public void setRentalStatus(String rentalStatus) {
		this.rentalStatus = rentalStatus;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}