
INSERT INTO C4_COMPANY_DETAILS (
COMPANY_OID, COMPANY_ID, COMPANY_NAME, PHONE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE
) VALUES (
'FFFFFFFFFFFFFFFF', 'C4CLOUD', 'C4 TECHNOLOGY SOLUTIONS','9849613769', 'AAAAAAAAAAAAAAAA',SYSDATE,'AAAAAAAAAAAAAAAA',SYSDATE
);

INSERT INTO C4_ROLE_DETAILS (ROLE_ID, ROLE_NAME, COMPANY_OID
) VALUES (
'RL100000', 'STANDARD_AGENT', 'FFFFFFFFFFFFFFFF'
);
INSERT INTO C4_ROLE_DETAILS (ROLE_ID, ROLE_NAME, COMPANY_OID
) VALUES (
'RL110000', 'STANDARD_CUSTOMER', 'FFFFFFFFFFFFFFFF'
);

INSERT INTO C4_USER_SECURITY (USER_OID,USERNAME,PASSWORD,STATUS,CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION
) VALUES (
'AAAAAAAAAAAAAAAA', 'upender0209@gmail.com', 'chinni', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 1
);

INSERT INTO C4_USER_DETAILS (
C4_USER_OID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ROLE_ID, COMPANY_OID
) VALUES (
'AAAAAAAAAAAAAAAA', 'upender0209@gmail', 'upender0209@gmail', 'Upender', 'Mamindlapelly', '9849613769', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'RL100000', 'FFFFFFFFFFFFFFFF'
);

INSERT INTO VRMS_USER_DETAILS (
C4_USER_OID, USERNAME, EMAIL, FIRST_NAME, LAST_NAME, MOBILE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ROLE_ID, COMPANY_OID
) VALUES (
'AAAAAAAAAAAAAAAA', 'upender0209@gmail', 'upender0209@gmail', 'Upender', 'Mamindlapelly', '9849613769', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'RL100000', 'FFFFFFFFFFFFFFFF'
);

INSERT INTO VRMS_AGENT_CUSTOMER_DETAILS (
AG_CUST_OID, AG_CUST_ID, FIRST_NAME, LAST_NAME, MOBILE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ROLE_ID, COMPANY_OID
) VALUES (
'BBBBBBBBBBBBBBBB', 'CUST2000', 'Bipin', 'Tiwari', '9542713769', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'RL110000', 'FFFFFFFFFFFFFFFF'
);

INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT100', '2024 TELUGU MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);
INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT101', '2023 HINDI MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);
INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT102', '2024 ENGLISH MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);
INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT103', '2024 TAMIL MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);
INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT104', '2023 TELUGU MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);
INSERT INTO VRMS_CATEGORY_DETAILS (
CATEGORY_ID, CATEGORY_NAME, ACTIVE_PRICE, INITIAL_PRICE, STATUS, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, COMPANY_OID
) VALUES (
'CAT105', '2023 MALAYALAM MOVIES', '50', '50', 'ACTIVE', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'FFFFFFFFFFFFFFFF'
);

INSERT INTO VRMS_MOVIE_DETAILS (
MOVIE_ID, MOVIE_NAME, CATEGORY_ID, COMPANY_OID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, STATUS, TOTAL_COPIES, AVAILABLE_COPIES
) VALUES (
'MV5000', 'SEETHA RAMAM', 'CAT104', 'FFFFFFFFFFFFFFFF', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'ACTIVE',5,5
);
INSERT INTO VRMS_MOVIE_DETAILS (
MOVIE_ID, MOVIE_NAME, CATEGORY_ID, COMPANY_OID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, STATUS, TOTAL_COPIES, AVAILABLE_COPIES
) VALUES (
'MV5001', 'RRR', 'CAT104', 'FFFFFFFFFFFFFFFF', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'ACTIVE',5,5
);
INSERT INTO VRMS_MOVIE_DETAILS (
MOVIE_ID, MOVIE_NAME, CATEGORY_ID, COMPANY_OID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, STATUS, TOTAL_COPIES, AVAILABLE_COPIES
) VALUES (
'MV5002', 'BRAHMASTRA', 'CAT101', 'FFFFFFFFFFFFFFFF', 'AAAAAAAAAAAAAAAA', SYSDATE, 'AAAAAAAAAAAAAAAA', SYSDATE, 'ACTIVE',5,5
);

COMMIT;