
-- DELETE THE TABLES IN THE REVERSED ORDER. DO NOT REVAMP THE ORDER OF TABLES IN DELETE SCRIPT.

DROP TABLE VRMS_TRNX_DETAILS;
DROP TABLE VRMS_AGENT_BONUS_DTLS;
DROP TABLE VRMS_RENTAL_DETAILS;
DROP TABLE VRMS_MOVIE_DETAILS;
DROP TABLE VRMS_CATEGORY_DETAILS;
DROP TABLE VRMS_AGENT_CUSTOMER_DETAILS;
DROP TABLE VRMS_USER_DETAILS;
DROP TABLE C4_USER_DETAILS;
DROP TABLE C4_ROLE_DETAILS;
DROP TABLE C4_USER_SECURITY;
DROP TABLE C4_COMPANY_DETAILS;
DROP TABLE C4_PRODUCT_DETAILS;